### PR TITLE
fixed LazyColumn's background, (surface) color issue

### PR DESCRIPTION
**Pull request by Ftm-amani**
Hello
Problem: I wasn't able to change backgound of lazy column
in surface we can't change background color from:
Surface( Modifier.bacground(Color.something) )

we should do something like this :
Surface( color = Color.something ){

### CODE REVIEW

**Comment by TuleSimon** [comment]
hi, sorry for the late reply, i will check it out and merge your PR

**Review by TuleSimon — APPROVED** [review]
nice work

**Comment by TuleSimon** [comment]
merged, please check the latest library version

**Comment by Ftm-amani** [comment]
Hi Mr Simon
I wanted to reach out and let you know that I am having trouble getting the code library to be recognized by my project after leatest update.
I have double checked my implementation and dependencies, but it still doesn't seem to be working. Can you please provide me with some guidance on how to resolve this issue?

**Comment by TuleSimon** [comment]
Sorry. I haven't pushed the least version 1.11 yet.. try again in 10minutes

**Comment by TuleSimon** [comment]
ok working now

**Pull request merged**
